fix: `getUploader` should only be called when a new `UploadPicker` instance is created
nextcloud/nextcloud-upload pull request #887
Opened 2023-07-08 22:37 UTC by susnux

Finally solved the issue with the `@nextcloud/cypress` update:

![image](https://github.com/nextcloud/nextcloud-upload/assets/1855448/7140f013-f260-4257-a27d-db1a39a712e7)

2023-07-09 09:19 UTC, skjnldsv approved these changes

2023-07-09 09:20 UTC, skjnldsv requested changes
Hum, I actually don't get why that would change anything ?
The uploader init is irrelevant to the Vue component. It doesn't matter if it's created before or while the vue component is initiated?

2023-07-09 13:49 UTC, susnux commented
@skjnldsv because before this the bundled file looks like this:

```js
const uploadManager = getUploader();
var UploadPicker = // ...
// ... more stuff ...
let _uploader = null
function getUploader() {
   /// ...
}
```

So as `uploadManager` is on the global scope, it will get initialized first by calling uploadManager() but `_uploader` was not declared at this time, as the interpreter is still on the `uploadManager` line.

With this changes it looks like this
```js
var UploadPicker  = {
    // ...
    data() {
        uploadManager: getUploader(),
        // ...
    }
}
// ... more stuff ...
let _uploader = null
function getUploader() {
   /// ...
}
```

so this time everything is declared first before it is used.


To see the error in action you can try this exampel in Node or your browser console:
```js
const uploadManager = getUploader()
let _uploader = null
function getUploader() {
   if (_uploader === null) return _uploader = 'uploader'
   return _uploader
}
```

The node error message is not that helpful I think:
> ReferenceError: Cannot access '_uploader' before initialization

But on Firefox it makes sense:
> Uncaught ReferenceError: **can't access lexical declaration** '_uploader' before initialization

2023-07-09 15:13 UTC, susnux commented
Found the reason for the cypress issue here and fixed that :)

2023-07-10 09:06 UTC, skjnldsv commented
Wow, this is very interesting!
The import order does make a difference in bundling, TIL

2023-07-10 09:06 UTC, skjnldsv approved these changes

2023-07-10 09:06 UTC, merged